export enum ErrorMessage {
  GMAIL_ALREADY_EXITS = 'Gmail already exits',
  GMAIL_INCORRECT = 'error.USER_NAME_INCORRECT',
  PASSWORD_INCORRECT = 'error.PASSWORD_INCORRECT',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  ACCOUNT_NOT_EXISTS = 'error.ACCOUNT_NOT_EXISTS',
  IDEA_NOT_EXIST = 'error.IDEA_NOT_EXIST',
  MIN_LENGTH_1 = 'error.MIN_LENGTH_1',
  YOU_DO_NOT_HAVE_PERMISSION_TO_POST_IDEA = 'error.YOU_DO_NOT_HAVE_PERMISSION_TO_POST_IDEA',
  FILE_PDF_MAX = 'error.FILE_PDF_MAX',
  YOU_DO_NOT_HAVE_RIGHTS_TO_REGISTER_USER_ACCOUNTS = 'error.YOU_DO_NOT_HAVE_RIGHTS_TO_REGISTER_USER_ACCOUNTS',
  IDEA_REACTION_PERMISSION = 'error.YOU_DO_NOT_HAVE_PERMISSION_TO_REACT_IDEA',
}
