export enum ErrorMessage {
  GMAIL_ALREADY_EXITS = 'Gmail already exits',
  GMAIL_INCORRECT = 'error.USER_NAME_INCORRECT',
  PASSWORD_INCORRECT = 'error.PASSWORD_INCORRECT',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  ACCOUNT_NOT_EXISTS = 'error.ACCOUNT_NOT_EXISTS',
  IDEA_NOT_EXIST = 'error.IDEA_NOT_EXIST',
}
